export const GET_LISTINGS_REQUEST = "GET_LISTINGS_REQUEST"
export const GET_LISTINGS_SUCCESS = "GET_LISTINGS_SUCCESS"
export const GET_LISTINGS_FAILURE = "GET_LISTINGS_FAILURE"

export const SINGLE_IMAGE_REQUEST = "SINGLE_IMAGE_REQUEST"
export const SINGLE_IMAGE_SUCCESS = "SINGLE_IMAGE_SUCCESS"
export const SINGLE_IMAGE_FAILURE = "SINGLE_IMAGE_FAILURE"

export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST"
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS"
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE"

export const POST_IMAGE_REQUEST = "POST_IMAGE_REQUEST"
export const POST_IMAGE_SUCCESS = "POST_IMAGE_SUCCESS"
export const POST_IMAGE_FAILURE = "POST_IMAGE_FAILURE"

export const EDIT_IMAGE_REQUEST = "EDIT_IMAGE_REQUEST"
export const EDIT_IMAGE_SUCCESS = "EDIT_IMAGE_SUCCESS"
export const EDIT_IMAGE_FAILURE = "EDIT_IMAGE_FAILURE"

export const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST"
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS"
export const DELETE_IMAGE_FAILURE = "DELETE_IMAGE_FAILURE"