export const GET_LISTINGS_REQUEST = "GET_LISTINGS_REQUEST"
export const GET_LISTINGS_SUCCESS = "GET_LISTINGS_SUCCESS"
export const GET_LISTINGS_FAILURE = "GET_LISTINGS_FAILURE"

export const SINGLE_IMAGE_REQUEST = "SINGLE_IMAGE_REQUEST"
export const SINGLE_IMAGE_SUCCESS = "SINGLE_IMAGE_SUCCESS"
export const SINGLE_IMAGE_FAILURE = "SINGLE_IMAGE_FAILURE"

export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST"
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS"
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE"