export const GET_LISTINGS_REQUEST = "GET_LISTINGS_REQUEST"
export const GET_LISTINGS_SUCCESS = "GET_LISTINGS_SUCCESS"
export const GET_LISTINGS_FAILURE = "GET_LISTINGS_FAILURE"

export const SINGLE_IMAGE_REQUEST = "SINGLE_IMAGE_REQUEST"
export const SINGLE_IMAGE_SUCCESS = "SINGLE_IMAGE_SUCCESS"
export const SINGLE_IMAGE_FAILURE = "SINGLE_IMAGE_FAILURE"